name: Install dependencies

runs:
  using: "composite"
  steps:
    - name: Install ruby & snap
      run: sudo apt update && sudo apt install ruby snapd
      shell: bash
    - name: Install bundle
      run: sudo gem install bundler
      shell: bash
    - name: Install flutter
      run: sudo snap install flutter --classic
      shell: bash
    - name: Install dependencies
      run: bundle install
      shell: bash
    - name: Flutter doctor
      run: flutter doctor -v
      shell: bash
