// Mocks generated by Mockito 5.0.7 from annotations
// in danger_flutter_coverage_demo/test/home_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:danger_flutter_coverage_demo/document.dart' as _i4;
import 'package:danger_flutter_coverage_demo/document_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i2.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Document> find(int? id) => (super.noSuchMethod(
      Invocation.method(#find, [id]),
      returnValue: Stream<_i4.Document>.empty()) as _i3.Stream<_i4.Document>);
  @override
  _i3.Stream<_i4.DocumentStatus> updateStatus(_i4.DocumentStatus? status) =>
      (super.noSuchMethod(Invocation.method(#updateStatus, [status]),
              returnValue: Stream<_i4.DocumentStatus>.empty())
          as _i3.Stream<_i4.DocumentStatus>);
}
